app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// Route::get('/', function () {
// 	return view('auth.login');
// });

//
	Route::get('/', 'RouterGetController@router');
	Route::post('/', 'RouterPostController@router');
	Route::delete('/', 'RouterDeleteController@router');
	
	
// 	Route::get('install', 'InstallController@migration');

// 	// Authentication routes...
// 	Route::get('auth/login', 'Auth\AuthController@getLogin');
// 	Route::get('login', 'Auth\AuthController@getLoginservicio');
// 	Route::get('insert', 'insertController@registro_usuario');//ruta para registrar usuarios
// 	Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
// 	Route::post('auth/login1', ['as' =>'auth/login1', 'uses' => 'Auth\AuthController@postLoginservicio']);
// 	Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);

		

// 	//SOLO LOS USUARIOS AUTENTICADOS PUEDEN VER ESTAS RUTAS
// 	Route::group(['middleware' => 'auth'], function () {
// 		//rutas tipo servicio
// 		Route::get('servicios', 'ServicioController@index');
// 		Route::get('servicios/create', 'ServicioController@create');
// 		Route::get('servicios/{id}', 'ServicioController@show');
// 		Route::get('servicios/{id}/edit', 'ServicioController@edit');
// 		Route::put('servicios/{id}', 'ServicioController@update');
// 		Route::post('servicios', 'ServicioController@store');
// 		Route::delete('servicios/{id}', 'ServicioController@destroy');
// 		Route::get('servicios/{id}/status/{status}', 'ServicioController@status');
// 		Route::get('servicios/destino/{id}', 'ServicioController@destino');
// 		Route::post('servicios/destino/editar/{id}', 'ServicioController@destinoEdit');
// 		Route::post('servicios/destino/nuevo', 'ServicioController@destinoNew');
// 		Route::delete('servicios/destino/eliminar/{id}', 'ServicioController@eliminar_destino');
// 		Route::delete('servicios/destino/eliminar_img/{id}', 'ServicioController@eliminar_destino_img');
// 		Route::get('servicios/misa/{id}', 'ServicioController@misa');
// 		Route::post('servicios/misa/editar/{id}', 'ServicioController@editar_misa');
// 		Route::post('servicios/misa/nuevo', 'ServicioController@nueva_misa');
// 		Route::delete('servicios/misa/eliminar/{id}', 'ServicioController@eliminar_misa');
// 		Route::delete('servicios/velatorio/eliminar/{id}', 'ServicioController@eliminar_velatorio');
// 		Route::get('servicios/sala/{id}', 'ServicioController@sala');
// 		Route::post('servicios/sala/editar/{id}', 'ServicioController@editar_sala');
// 		Route::post('servicios/sala/nueva', 'ServicioController@nueva_sala');
// 		Route::delete('servicios/sala/eliminar/{id}', 'ServicioController@eliminar_sala');
// 		Route::delete('servicios/sala/eliminar_ico/{id}', 'ServicioController@eliminar_sala_icono');
// 		Route::delete('servicios/sala/eliminar_img/{id}', 'ServicioController@eliminar_sala_img');
// 		Route::delete('servicios/eliminar_img/{id}', 'ServicioController@eliminar_img_serv');

// 		// Salas
// 		Route::get('salas', 'SalaController@index');
// 		Route::get('salas/{id}', 'SalaController@show');
// 		Route::post('salas', 'SalaController@store');
// 		Route::post('salas/{id}', 'SalaController@update');
// 		Route::delete('salas/{id}', 'SalaController@destroy');

// 		//rutas tipo velatorio
// 		Route::delete('velatorios/{id}', 'VelatorioController@destroy');

// 		//rutas tipo empresa
// 		Route::post('empresas', 'EmpresaController@store');

// 		//rutas tipo responso misa
// 		Route::post('responso/misa', 'ResponsoController@store');
		
// 		//Routes for licencia
// 		Route::get('config/licencia', 'LicenciaController@show');
// 		Route::post('config/licencia', 'LicenciaController@update');
// 		Route::post('config/licencia/validar', 'LicenciaController@check_license');
// 		Route::delete('config/licencia/{id}', 'LicenciaController@delete');

		
// 		//Routes for resource Config
// 		Route::get('config', 'ConfigController@index');
// 		Route::get('config/configuracion', 'ConfigController@configuracion');
// 		Route::post('config/configuracion', 'ConfigController@configuracionStore');

// 		//Route::post('config', 'StylesController@store');
// 		//Routes for resource cv
// 		Route::get('config/cv', 'CVController@index');
// 		Route::post('config/cv', 'CVController@store');
// 		  //Routes for resource cs
// 		Route::get('config/cs', 'CSController@index');
		
// 		Route::post('config/cs', 'CSController@store');
// 		//Routes for resource ch
// 		Route::get('config/ch', 'CHController@index');
// 		Route::get('config/ch/sync/servicios', 'CHController@sync');
// 		Route::get('config/conexion', 'CHController@conexion');
// 		//Route::post('config/ch/sync/servicios', 'CHController@sync1');
// 		Route::post('config/ch', 'CHController@store');
// 		Route::post('config/ch/asociarSalas', 'CHController@asociarSalas'); 
// 		// RUTAS NI
// 		Route::get('config/ni', 'NIController@index');
// 		Route::post('config/ni', 'NIController@store');
// 		//Rutas de Homenaje
// 		Route::get('servicios/{id}/homenajes', 'HomenajeController@index');
// 		Route::post('servicios/{id}/homenajes', 'HomenajeController@store');
// 		Route::get('servicios/{id}/{accion}/homenajesHide', 'HomenajeController@update');
// 		Route::delete('servicios/{id}/homenajes', 'HomenajeController@destroy');
// 		Route::get('homenaje/{id}', 'HomenajeController@show');

// 		Route::get('productos','ProductoController@index');
// 		Route::post('productos', 'ProductoController@store');
// 		Route::post('productos/{id}', 'ProductoController@update');

// 	});
	
	
// 	//API
// 	Route::get('api/servicios', 'ServicioController@api_showAll');
// 	Route::get('api/servicios/{id}', 'ServicioController@api_show');
// 	Route::get('api/servicios_por_sala/{salas}', 'ServicioController@api_show_by_room');
// 	//Route::get('api/styles', 'StylesController@api_showAll');
// 	//Route::get('api/styles/{id}', 'StylesController@api_show');
// 	Route::get('api/homenaje', 'HomenajeController@api_showAll');
// 	Route::get('api/homenaje/{id}', 'HomenajeController@api_show');
// 	Route::delete('api/homenaje/{id}', 'HomenajeController@api_delete');
// 	Route::get('api/servicios/{id}/homenajes', "HomenajeController@api_showAll");
// 	Route::get('api/config/cv', 'CVController@api_config');
// 	Route::get('api/config/cs', 'CSController@api_config');
// 	Route::get('api/config/ch', 'CHController@api_config');
// 	Route::get('api/config/ni', 'NIController@api_config');
// 	Route::post('api/config/ch/sala', 'CHController@api_sala');
// 	Route::post('api/config/cv/salas', 'CVController@api_salas');
// 	Route::get('api/productos', 'ProductoController@api_showAll');
// 	Route::get('api/salas', 'CSController@api_salas');

// 	Route::get('servicio/sala/{id}', 'ServicioController@sala');
// 	//DEBUGGING ALL QUERYS
// 	/*Event::listen('illuminate.query', function($query)
// 	{
// 		var_dump($query);
// 	});*/
// 	Route::get('api/ip', 'ServicioController@ip');

// 	// Validación de la licencia desde las carteleras
// 	Route::get('api/licencia/{product_id}', 'LicenciaController@validar');
	
// 	// API Store empresa
// 	Route::get('api/empresa/index', 'EmpresaController@api_index');
// 	Route::post('api/empresa', 'EmpresaController@api_store');
// 	Route::post('api/empresa/editar/{id}', 'EmpresaController@cambio');
// 	Route::delete('api/empresa/eliminar/{id}', 'EmpresaController@destroy');
	
// 	// API Store responso
// 	Route::post('api/responso', 'ResponsoController@api_store');

// 	//plugin worpress
// //  Route::group( ['middleware' => 'cors'], function(){
// 		Route::get('plugin/servicios', 'ServicioController@servicios_plugin');
// 		Route::get('plugin/servicio/{id}', 'ServicioController@servicio_plugin');
// 		Route::get('plugin/homenajes', 'ServicioController@homenajes_plugin');
// 		Route::get('plugin/homenaje/{id}', 'ServicioController@homenaje_plugin');
// //  });

app/Homenaje.php
<?php 
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use App\Servicio;

class Homenaje extends Model {

    const FOTO_DIR = 'images/homenaje/';
    public $timestamps = false;


    // Relationships
    public function servicio()
    {
        return $this->belongsTo(Servicio::class);
    }

    public function scopeToServicio($query,$servicio)
    {
        return $query->where("servicio_id",$servicio);
    }

    //Accesores

    public function getFotoAttribute($value)
    {
        return Homenaje::FOTO_DIR.$value;
    }

}

app/Servicio.php
<?php 
namespace App;

use App\Homenaje;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Carbon\Carbon;

class Servicio extends Model {

	public $timestamps = false;

    const FOTO_URL = 'images/servicios/';
    
    protected $dates = [
        'salida',
        'fecha_inicio',
        'fecha_fin'
    ];

    protected $fillable = ['responso_id','empresa_id'];
     
	public function scopeSala($query, $sala){
		$rs = $query->where('salas_id', $sala);
		return $rs;
	}


	public static function formatHour($hour){
		$aux = explode(' ', $hour);
		$aux2 = explode(':',$aux[0]);

		if($aux[1] == 'PM'){
			$aux2[0]+=12;
		}
		return $aux2[0].':'.$aux2[1].':00'; 
	}

	public function salas()
    {
        return $this->belongsTo(Sala::class);
    }

    public function homenajes()
    {
        return $this->hasMany(Homenaje::class);
    }

	public function velatorios(){
		return $this->hasMany('App\Velatorio');
	}

	public function sala(){
		return $this->belongsTo('App\Sala');
	}

	public function religion(){
		return $this->belongsTo('App\Religion');
	}

	public function destino(){
		return $this->belongsTo('App\Destino');
	}
    public function misa(){
        return $this->belongsTo('App\Responso','responso_id');
    }
    public function empresa(){
        return $this->belongsTo('App\Empresa','empresa_id');
    }


	/*public static function descargarImagen($url,$name){
		$ch = curl_init ( $url );
        curl_setopt( $ch , CURLOPT_HEADER, 0);
        curl_setopt( $ch , CURLOPT_RETURNTRANSFER, 1);
        $raw=curl_exec( $ch );
        curl_close ( $ch );
        $cake = explode('.', $url);
        $ext = array_pop($cake);
        $name2 = 'servicios/'.$name.'.'.$ext;
        Storage::put($name2, $raw);

        return $name.'.'.$ext;
	}*/

	/*public static function getServices(){
		$curl = curl_init();
        curl_setopt_array($curl, array(
         CURLOPT_RETURNTRANSFER => 1,
         CURLOPT_URL => 'http://homenaje.de/wp-content/plugins/neo_homenajes/json/conector.php',
         CURLOPT_USERAGENT => 'Request services',
         CURLOPT_POST => 1,
         CURLOPT_POSTFIELDS => array(
            'listar' => ''
         )
        ));
        
        $resp = curl_exec($curl);
        curl_close($curl);

        return $resp;
	}

	public static function AllHomenajes(){
	    $curl = curl_init();
        curl_setopt_array($curl, array(
         CURLOPT_RETURNTRANSFER => 1,
         CURLOPT_URL => 'http://homenaje.de/wp-content/plugins/neo_homenajes/json/conector.php',
         CURLOPT_USERAGENT => 'Request homenajes',
         CURLOPT_POST => 1,
         CURLOPT_POSTFIELDS => array(
            'homenaje' => ''
         )
        ));
        
        $resp = curl_exec($curl);
        curl_close($curl);

        return $resp;

	}*/

}

resources/views/servicios/create.blade.php
@extends('dashboard.layout.base')



@section('section')
    Servicios
@stop

{{-- 
@section('breadcrumb')
    Formulario
@stop 
--}}

@section('content')
<?php 
    $usuario = session()->get('key_login'); 

    if(!isset($usuario['nombre']) || $usuario['admin']!=1){        
      echo '<script> location.href = "./?ruta=login"; </script>';
    }
?>
    @include('servicios.form')
@stop

resources/views/servicios/index.blade.php
    @extends('dashboard.layout.base')

@section('title')
    Servicios
@stop

@section('section')
    Servicios
@stop

@section('breadcrumb')
    Lista de servicios
@stop

@section('content')
<?php 
    $usuario = session()->get('key_login'); 

    if(!isset($usuario['nombre']) ){        
      echo '<script> location.href = "./?ruta=login"; </script>';
    }
?>


<?php 
    use Illuminate\Http\RedirectResponse;
    use Illuminate\Routing\Redirector;
    use App\CH;

    $CH = CH::cliente(1)->first();

    //if($CH->tipo_servidor=='local' || $CH->tipo_servidor=='online'){
        
      //  echo '<script> location.href = "config/ch"; </script>';
    //}

?>

        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">&nbsp;<a  href="{{ url('/?ruta=servicios/create') }}" id="agregar" style="cursor:pointer; cursor: hand" class="borrar btn btn-info" title="Nuevo Servicio"><i class="ace-icon glyphicon glyphicon-plus"></i>Nuevo </a></h3>
                    
                     <span class="input-icon form-search nav-search pull-right" style="padding-top: 5px">
                        <input  id="buscar"  type="text" autocomplete="off" id="nav-search-input" style="width: 13em" class="nav-search-input" placeholder="Buscar ...">

                    </span>
                </div>

    
                <!-- /.box-header -->
                <div class="box-body">
                <table class="table table-hover" id="tabla">
                    <thead>
                        <tr>
                          {{-- <th>ID</th> --}}
                          <th>Sala</th>
                          <th></th>
                          
                          <th>Nombre</th>
                          <th>Ingreso</th>
                          <th>Salida</th>                          
                          <th>Homenajes</th>
                          <th>Estado</th>
                          <th class="text-center"></th>
                        </tr>
                    </thead>
                 @foreach($servicio as $value)

                  @include("servicios.partials.delete")
                  
                    <tr>
                        {{-- <td width="5%">{{$value->id}}</td> --}}
                        <td>
                            @if(isset($value->sala->nombre))
                                {{$value->sala->nombre}}
                                
                               
                            @endif
                             @if($value->sala_id==0)
                                En Domicilio
                            @endif
                             @if($value->sala_id==99)
                                En Privado
                            @endif
                        </td>
                        <td width="10%"><img src="{{url($value->foto)}}" alt="{{$value->foto}}" width="50%"></td>
                        
                        <td >{{$value->nombres." ".$value->apellidos}}</td>
                        <td width="12%">{{\Carbon\Carbon::parse($value->fecha_inicio )->format('d/m')}} {{\Carbon\Carbon::parse($value->fecha_inicio )->format('H:i')}}</td>
                        <td width="12%">{{\Carbon\Carbon::parse($value->salida )->format('d/m')}} {{\Carbon\Carbon::parse($value->salida )->format('H:i')}}</td>
                      
                        
                        <td>
                            <a href="{!! url('/?ruta=servicios/homenajes&id='.$value->id)  !!}" class="btn btn-xs bg-purple fa fa-eye" title="Ver Homenajes"> ({{ count($value->homenajes) }})</a>   
                        </td>
                        <td>
                            @if($value->status=="0")
                                <a href="{{url('/?ruta=servicios/status&id='.$value->id.'&status=inactivar')}}"  data-homenaje="{{ $value->toJson() }}" class="btn btn-xs btn-success btn-status" title="Inactivar servicio">
                                    Activo
                                </a>
                            @elseif($value->status=="1")
                                <a href="{{url('/?ruta=servicios/status&id='.$value->id.'&status=activar')}}"  data-homenaje="{{ $value->toJson() }}" class="btn btn-xs btn-danger btn-status" title="Activar servicio">
                                    Inactivo
                                </a>
                            @endif
                        </td> 
                        <td width="10%">
                            <a href="{{url("/?ruta=servicios/ver&id=$value->id")}}"
                               class="btn btn-xs btn-primary" title="Editar Servicio">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <button type="button"  onclick="eliminarServicio({{$value->id}})" class="btn-delete-servicio btn btn-xs btn-danger" title="Eliminar Servicio">
                                <i class="fa fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    
                  @endforeach 

              </table>
                </div>
            </div>
        </div>
        <!--Eliminar servicio-->
<div class="modal fade" role="dialog" id="modelEliminar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Eliminar Servicio</h4>
            </div>
            <div class="modal-body">
                
               <input type="hidden" name="servicio_id" id="servicio_id_eliminar" >
                <p>¿Seguro que desea eliminar el servicio?</p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" onclick="confirmarEliminarServicio()" id="btntitle">Eliminar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
        
@stop
@section('script')


   
    <script>
        function eliminarServicio(x){
            
            $('#servicio_id_eliminar').val(x);
            $('#modelEliminar').modal('toggle');
            
        }
        function confirmarEliminarServicio(){
            var id = $('#servicio_id_eliminar').val();
            // console.log(id);
            $.ajax({
                type:'DELETE',
                url: "./?ruta=servicios/delete&id="+id, 
                data :{
                    '_token': '{{ csrf_token() }}'				
                },
                success: function(result){
                    // console.log(result);
                    $('#modelEliminar').modal('toggle');
                    location.reload();
                    
                },error:function(err){
                    console.log(err);
                }
            });
        }
        var myTable = $("#tabla") .DataTable( {
            "dom": '<"top"i>rt<"row"<"col-xs-6"l><"col-xs-6"p>>',
            "length":   false,
            "info":     false,
            "bSort": true,
            "aaSorting":[[1,'desc']],
            bAutoWidth: false,
            select: {
                style: 'multi'
            }
        } );
    
        $('#buscar').on( 'keyup', function () {
            myTable.search( this.value ).draw();
        } );

    $(document).ready(function(){
        // $('.btn-delete-servicio').on('click', function(){
        // servicio = $(this).data('servicio');
        // $("#servicio_id").val(servicio.id);
        // $("#title").html("Eliminar Servicio "+servicio.nombres+" "+servicio.apellidos);
        // $("#btntitle").html("Eliminar");
        // $("#modalDelete").modal();
        // });
    });
    </script>
@stop

resources/views/servicios/sync.blade.php
@extends('dashboard.layout.base')

@section('title')
    Servicios
@stop

@section('section')
    Servicios
@stop

@section('breadcrumb')
    Lista de servicios
@stop

@section('content')
<h3 class="box-title"></h3>
   {{$servicios}}



@stop